
alleles_B_N <- as.data.frame(matrix(nrow=population_size_dispersal*2,ncol = length(location_neutral_loci_analysis)))
alleles_B_B <- as.data.frame(matrix(nrow=population_size_dispersal*2,ncol = length(location_neutral_loci_analysis)))
alleles_W_L <- as.data.frame(matrix(nrow=population_size_dispersal*2,ncol = length(location_neutral_loci_analysis)))
alleles_fdist_sim <- as.data.frame(matrix(nrow=population_size_dispersal*2,ncol = length(location_neutral_loci_analysis)))
FST_fdist_sim <- rep(list(as.data.frame(matrix(ncol=4,nrow=population_size_dispersal*2))),length(1))
input_fdist <- as.data.frame(matrix(ncol=9,nrow= length(location_neutral_loci_analysis)))
Shannon_fdist_sim <- as.data.frame(matrix(ncol=6,nrow= (length(location_neutral_loci_analysis)*1)))
hierf <- rep(list(as.data.frame(matrix(c(rep(1, population_size_dispersal),rep(2, population_size_dispersal)), nrow = population_size_dispersal * 2))),length(location_neutral_loci_analysis))
hierf_W_L <- as.data.frame(matrix(c(rep(1, population_size_dispersal),rep(2, population_size_dispersal)),nrow = population_size_dispersal * 2))

AFD <- rep(list(as.data.frame(matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))

sha_pop1 <- rep(list(as.data.frame(matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
sha_pop2 <- rep(list(as.data.frame(matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
sha_pops <- rep(list(as.data.frame(matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
shua <- rep(list(as.data.frame(matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
first_sha_pop1 <- rep(list(as.data.frame(matrix(ncol = 1, nrow = 1))),length(location_neutral_loci_analysis))
first_sha_pop2 <- rep(list(as.data.frame(matrix(ncol = 1, nrow = 1))),length(location_neutral_loci_analysis))
expected_sha_pop1 <- rep(list(as.data.frame(matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
expected_sha_pop2 <- rep(list(as.data.frame( matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
first_het_pop1 <- rep(list(as.data.frame(matrix(ncol = 1, nrow = 1))),length(location_neutral_loci_analysis))
first_het_pop2 <- rep(list(as.data.frame(matrix( ncol = 1, nrow = 1))),length(location_neutral_loci_analysis))
expected_het_pop1 <- rep(list(as.data.frame(matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
expected_het_pop2 <- rep(list(as.data.frame(matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
het_pop1 <-rep(list(as.data.frame(matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
het_pop2 <- rep(list(as.data.frame( matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
het_ave <- rep(list(as.data.frame(matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
Ht <- rep(list(as.data.frame(matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
Fst <- rep(list(as.data.frame(matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
Fstp <- rep(list(as.data.frame(matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
Dest <- rep(list(as.data.frame( matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
sha_diff <- rep(list(as.data.frame( matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
one_D_beta <- rep(list(as.data.frame( matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
one_D_alpha_pop1 <- rep(list(as.data.frame( matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
one_D_alpha_pop2 <- rep(list(as.data.frame( matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
two_D_alpha_pop1 <- rep(list(as.data.frame( matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
two_D_alpha_pop2 <- rep(list(as.data.frame( matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
two_D_gamma <- rep(list(as.data.frame( matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
two_D_alpha_average <- rep(list(as.data.frame( matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
two_D_beta <- rep(list(as.data.frame( matrix(ncol = 1, nrow = gen_number_dispersal))),length(location_neutral_loci_analysis))
deleterious_eliminated <- data.frame(matrix(nrow = gen_number_dispersal, ncol = 1))
mean_h_final <- data.frame(matrix(nrow = gen_number_dispersal, ncol = 1))
mean_s_final <- data.frame(matrix(nrow = gen_number_dispersal, ncol = 1))
g_load_m_final <- data.frame(matrix(nrow = gen_number_dispersal, ncol = 1))
g_load_a_final <- data.frame(matrix(nrow = gen_number_dispersal, ncol = 1))
